"""app_id col added session model

Revision ID: 6a58df2c09c9
Revises: 9b6a914d8948
Create Date: 2026-09-29 21:10:36.220724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a58df2c09c9'
down_revision: Union[str, Sequence[str], None] = '9b6a914d8948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('app_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sessions', 'applications', ['app_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'app_id')
    # ### end Alembic commands ###
