"""Oauth model modified to save app details

Revision ID: 776321f14fbf
Revises: a83ad2da12f2
Create Date: 2026-10-02 20:16:56.000020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776321f14fbf'
down_revision: Union[str, Sequence[str], None] = 'a83ad2da12f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_accounts', sa.Column('app_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'oauth_accounts', 'applications', ['app_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oauth_accounts', type_='foreignkey')
    op.drop_column('oauth_accounts', 'app_id')
    # ### end Alembic commands ###
