"""application model for auth service

Revision ID: 9b6a914d8948
Revises: 0575facdcf42
Create Date: 2026-09-28 21:06:59.817437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b6a914d8948'
down_revision: Union[str, Sequence[str], None] = '0575facdcf42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.add_column('users', sa.Column('app_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_app_email', 'users', ['app_id', 'email'])
    op.create_unique_constraint('unique_app_username', 'users', ['app_id', 'username'])
    op.create_foreign_key(None, 'users', 'applications', ['app_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint('unique_app_username', 'users', type_='unique')
    op.drop_constraint('unique_app_email', 'users', type_='unique')
    op.drop_column('users', 'app_id')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
