"""Refreshtoken model changes for JWT auth

Revision ID: a83ad2da12f2
Revises: 6a58df2c09c9
Create Date: 2026-09-30 20:14:44.794181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83ad2da12f2'
down_revision: Union[str, Sequence[str], None] = '6a58df2c09c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('app_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'refresh_tokens', 'applications', ['app_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_column('refresh_tokens', 'app_id')
    # ### end Alembic commands ###
