"""created family_id for refresh token mapping

Revision ID: f7022aee4b45
Revises: 6485fa20be3c
Create Date: 2026-09-15 21:21:45.197628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7022aee4b45'
down_revision: Union[str, Sequence[str], None] = '6485fa20be3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add column as nullable first to handle existing rows
    op.add_column('refresh_tokens', sa.Column('family_id', sa.String(length=64), nullable=True))

    # 2. Backfill existing rows with random family_id
    op.execute("UPDATE refresh_tokens SET family_id = md5(random()::text) WHERE family_id IS NULL")

    # 3. Enforce NOT NULL constraint
    op.alter_column('refresh_tokens', 'family_id', nullable=False)

    # 4. Create index
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'family_id')
    # ### end Alembic commands ###
